apps/xp/urls.py
from django.conf.urls import url
from django.urls import path
from apps.xp.views import CrearHistorias, CrearTareas, ActualizarHistorias, eliminarHistoria, index, crearCiclo, agregar_integrantes, obtener
from apps.xp import views
app_name = 'xp'

urlpatterns = [
    path('CrearHistorias/', CrearHistorias.as_view(), name='CrearHistorias'),
    path('CrearTareas/', CrearTareas.as_view(), name='CrearTareas'),
    path('ActualizarHistorias/<int:pk>', ActualizarHistorias.as_view(), name='ActualizarHistorias'),
    path('eliminar_historias/<int:id>', eliminarHistoria, name='eliminar_historias'),
    path('index-xp/<int:id>', index, name='index-xp'),
    path('crearCiclo', crearCiclo, name='crearCiclo'),
    path('agregar_integrantes', agregar_integrantes, name="agregar_integrantes"),
    path('obtener', obtener, name='obtener'),
    path('confirmar', views.confirmar, name='confirmar'),
    path('update_history', views.update_history, name='update_history'),
    path('show_crear_ciclo', views.show_crear_ciclo, name='show_crear_ciclo'),
    path('add_history_ciclo', views.add_history_ciclo, name='add_history_ciclo'),
    path('update_history_ciclo', views.update_history_ciclo, name='update_history_ciclo'),

]

way/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('apps.usuarios.urls')),
    url(r'^admin/', admin.site.urls),
     #url(r'^base/', include ('templates.base.urls')),
    url(r'^usuarios/', include ('apps.usuarios.urls')),
    url(r'^proyecto/', include ('apps.proyecto.urls')),
    url(r'^scrum/', include ('apps.scrum.urls')),

    path('xp/',include('apps.xp.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='usuarios/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='usuarios/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='usuarios/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='usuarios/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

#configuracion de rutas para imagenes
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/xp/models.py
from django.db import models
from apps.proyecto.models import Proyecto

# Create your models here.


class XP(models.Model):
    proyecto = models.ForeignKey(Proyecto, null=True, blank=True, on_delete=models.CASCADE)


class Ciclo(models.Model):
    f_inicio = models.DateTimeField()
    f_fin = models.DateTimeField()
    id_xp = models.ForeignKey(XP, null=True, blank=True, on_delete=models.CASCADE)
    estado = models.BooleanField(null=True, blank=True)

apps/xp/forms.py
from django import forms

from apps.scrum.models import HistoriaUsuario, Sbacklog


class HistoriaUsuarioXPForm(forms.ModelForm):
    class Meta:
        model = HistoriaUsuario

        fields = ['como_usuario', 'quiero', 'para', 'estado','id_xp','get']

        labels = {
            'como_usuario':'Perfil del Usuario',
            'quiero':'Requisito del usuario',
            'para':'Objectivo del requisito',
        }

        widgets = {
            'como_usuario':forms.TextInput(attrs={
                'class':'form-control',
            }),
            'quiero':forms.Textarea(attrs={
                'class':'form-control',
                'rows': '2',
            }),
            'para': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': '2',
            }),
            'id_xp':forms.TextInput(attrs={
                'type':'hidden'
            })
        }

apps/xp/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.db.models import Count, Q, Sum
from django.views.generic import View, CreateView, UpdateView, ListView, DetailView

from apps.xp.models import XP, Ciclo
from apps.xp.forms import HistoriaUsuarioXPForm
from apps.scrum.models import HistoriaUsuario, Sbacklog
from apps.scrum.forms import SbacklogForm
from apps.proyecto.models import ProUser, Proyecto, Rol
from apps.usuarios.models import User
from datetime import datetime
# Create your views here.


class CrearHistorias(View):
    model = HistoriaUsuario
    form_class = HistoriaUsuarioXPForm
    template_name = 'xp/historia_usuario.html'
    #success_url = reverse_lazy('usuarios:index')

    def get_context_data(self,*args):
        h = HistoriaUsuario.objects.filter(id_xp=args[1]).annotate(
            tareas=Count('sbacklog__id')
        )
        t = Sbacklog.objects.values('id_historia__quiero','nombre','n_horas').filter(id_historia__id_xp=args[1])
        xp = args[1]
        id_pro = XP.objects.values('proyecto').get(id=xp)
        contexto = {
            'form':self.form_class,
            'historias':h,
            'xp':xp,
            'tareas':t,
            'id_pro':id_pro['proyecto']
        }
        return contexto

    def get(self,request,*args,**kwargs):
        xp = request.session['xp']
        return render(request,self.template_name,self.get_context_data(self,xp))

    def post(self, request,*args, **kwargs):
        form = self.form_class(request.POST)
        print('datos del formularaio',form)
        if form.is_valid():
            form.save()

        return redirect('xp:CrearHistorias')


def index(request, id):
    task = Sbacklog.objects.filter(
        id_historia__get = True,
        id_historia__id_ciclo__id_xp__proyecto=id,
        estado=False,
        get=False
    )

    requisitos = HistoriaUsuario.objects.filter(
        id_xp__proyecto__id=id,
        get=True,
        id_ciclo__estado=True,
        id_ciclo__id_xp__proyecto=id,
        estado=False
    )

    proceso = Sbacklog.objects.filter(
        id_historia__get = True,
        id_historia__id_ciclo__id_xp__proyecto=id,
        estado=False,
        get=True
    )


    historias = HistoriaUsuario.objects.filter(id_xp__proyecto__id=id, get=False).annotate(
        dias=Sum('sbacklog__n_horas'),
        tareas=Count('sbacklog__id')
    )

    terminadas = Sbacklog.objects.filter(
        estado=True,
        id_historia__id_ciclo__id_xp__proyecto=id,
        id_historia__id_ciclo__estado=True
    )

    integrantes = User.objects.values('id','first_name','last_name').filter(prouser__proyecto=id)


    xp = XP.objects.values('id','proyecto__id','proyecto__nombre','proyecto__f_inicio','proyecto__f_fin').get(proyecto=id)

    resumen_pro = resumen(id)

    resumen_proyecto = resumen_pro['proyecto']
    resumen_historias = resumen_pro['historias']
    resumen_tareas = resumen_pro['tareas']
    resumen_integrantes = resumen_pro['integrantes']
    resumen_ciclo = resumen_pro['ciclo']
    resumen_ciclo_historias = resumen_pro['ciclo_historias']
    try:
        ciclo = Ciclo.objects.get(id_xp__proyecto=id,estado=True)
    except:
        ciclo = ""

    xp_f_inicio = datetime.strftime(xp['proyecto__f_inicio'], '%Y-%m-%d')
    xp_f_fin =  datetime.strftime( xp['proyecto__f_fin'], '%Y-%m-%d')

    print('inicio: ',xp_f_inicio, ' fin :',xp_f_fin)


    contexto = {
        'requisitos':requisitos,
        'xp':xp,
        'pendientes':task,
        'historias': historias,
        'integrantes':integrantes,
        'procesos':proceso,
        'terminadas':terminadas,
        'ciclo':ciclo,
        'resumen_proyecto':resumen_proyecto,
        'resumen_historias':resumen_historias,
        'resumen_tareas':resumen_tareas,
        'resumen_integrantes':resumen_integrantes,
        'resumen_ciclo':resumen_ciclo,
        'resumen_ciclo_historias':resumen_ciclo_historias,
        'id_pro':id,
        'xp_f_inicio': xp_f_inicio,
        'xp_f_fin': xp_f_fin
    }

    return render(request, 'xp/index-xp.html', contexto)


class CrearTareas(CreateView):
    model = Sbacklog
    form_class = SbacklogForm
    template_name = 'xp/historia_usuario.html'
    success_url = reverse_lazy('xp:CrearHistorias')


class ActualizarHistorias(UpdateView):
    model = HistoriaUsuario
    form_class = HistoriaUsuarioXPForm
    template_name = 'xp/actualizar_historia.html'
    success_url = reverse_lazy('xp:CrearHistorias')


def eliminarHistoria(request, id):
    if request.method == 'GET':
        h = HistoriaUsuario.objects.get(id=id)
        h.delete()
    return redirect('xp:CrearHistorias')


def crearCiclo(request):
    #Todos los derechos reservados por Maycol Cuero Ruiz

    if request.method == "POST":
        f_inicio = request.POST['f_inicio']
        f_fin = request.POST['f_fin']
        id_xp = request.POST['id_xp']
        id_historia = request.POST['idh'].split(',')

        xp = XP.objects.get(id=id_xp)
        #Crear Ciclo
        ciclo = Ciclo.objects.create(f_inicio=f_inicio,f_fin=f_fin,estado=True, id_xp=xp)
        if id_historia and id_historia != ['']:
            for h in id_historia:
                HistoriaUsuario.objects.filter(id=h).update(id_ciclo=ciclo.id, get=True)

    return JsonResponse({'datos':'resividos'})


def integrante_historia(request):
    if request.method == "POST":
        id_historia = request.POST['id_historia']
        id_usuario = request.POST['id_usuario']

    return JsonResponse('datos enviados')


def agregar_integrantes(request):
    if request.method == "POST":
        proyecto = request.POST['idpro']
        email = request.POST['email']
        rol = request.POST['rol']
        dato = "SI"
        us = "SI" #ayuda a verificar si el usuario ya existe
        try:
            usuario = User.objects.get(email=email)
        except:
            dato ="NO"

        if dato == "SI":
            u = ProUser.objects.filter(proyecto=proyecto, usuario=usuario.id)
            if u:
                us = "SI"
            else:
                us = "NO"

        if dato == "SI" and us == "NO":
            idpro = Proyecto.objects.get(id=proyecto)
            rol = Rol.objects.get(nombre=rol)
            ProUser.objects.create(proyecto=idpro, usuario = usuario, rol = rol)
            integrantes = User.objects.values('id', 'first_name', 'last_name').filter(prouser__proyecto=idpro.id)
            datos = {'datos_integrantes': render_to_string('clean/xp/integrantes.html', {'integrantes': integrantes})}
            return JsonResponse(datos)
        else:
            dato = "NO"
            return JsonResponse({'datos':dato})


def datos_actualizacion_tabla(id):
    task = Sbacklog.objects.filter(
        id_historia__get=True,
        id_historia__id=id,
        estado=False,
        get=False
    )
    proyecto = Proyecto.objects.get(xp__historiausuario__id=id)

    requisitos = HistoriaUsuario.objects.filter(
        id_xp__proyecto__id=proyecto.id,
        get=True,
        id_ciclo__estado=True,
        id_ciclo__id_xp__proyecto=proyecto.id,
        estado=False
    )

    proceso = Sbacklog.objects.filter(
        id_historia__get=True,
        id_historia__id=id,
        estado=False,
        get=True
    )

    historias = HistoriaUsuario.objects.filter(id=id, get=False).annotate(
        dias=Sum('sbacklog__n_horas'),
        tareas=Count('sbacklog__id')
    )

    terminadas = Sbacklog.objects.filter(
        estado=True,
        id_historia__id=id,
        id_historia__id_ciclo__estado=True
    )

    contexto = {
        'requisitos': requisitos,
        'pendientes': task,
        'historias': historias,
        'procesos': proceso,
        'terminadas': terminadas
    }

    return contexto


def obtener(request):
    if request.method == "GET":
        id = request.GET['id_tarea']
        u = request.user.pk
        Sbacklog.objects.filter(id=id).update(usuario=u, get=True, estado=False)
        historia = HistoriaUsuario.objects.get(sbacklog__id=id)

        contexto = datos_actualizacion_tabla(historia.id)


    datos = {'tabla_xp': render_to_string('clean/xp/tabla.html', contexto)}
    return JsonResponse(datos)


def confirmar(request):
    id = request.GET['id_tarea']

    Sbacklog.objects.filter(id=id).update(estado=True)

    # Consulto la historia de usuario
    h = HistoriaUsuario.objects.filter(sbacklog__id=id)

    # calculo si las tareas perteneciente a la misma historia de usuarios q ya estan completadas
    a = Sbacklog.objects.filter(id_historia=h[0].id).count()
    b = Sbacklog.objects.filter(id_historia=h[0].id, estado=True).count()

    # obtengo el procentaje de tareas cumplidas y dependiendo del resultado actualizo el modelo HistoriaUsuario
    x = (b * 100) / a
    if x == 100:
        HistoriaUsuario.objects.filter(id=h[0].id).update(estado=True)

    ciclo = Ciclo.objects.get(historiausuario__id=h[0].id)

    historias_ciclo = HistoriaUsuario.objects.filter(id_ciclo=ciclo.id).count()
    hcp = HistoriaUsuario.objects.filter(id_ciclo=ciclo.id,estado=True).count()

    hr = (hcp * 100) / historias_ciclo

    if hr == 100:
        Ciclo.objects.filter(id=ciclo.id).update(estado=False)

    datos = datos_actualizacion_tabla(h[0].id)

    info = {'tabla_xp': render_to_string('clean/xp/tabla.html', datos)}
    return JsonResponse(info)


def resumen(id_proyecto):

    xp = XP.objects.values('id', 'proyecto__id', 'proyecto__nombre', 'proyecto__f_inicio', 'proyecto__f_fin').get(
        proyecto=id_proyecto)

    historias = HistoriaUsuario.objects.filter(id_xp__proyecto__id=id_proyecto).annotate(
        dias=Sum('sbacklog__n_horas'),
        tareas=Count('sbacklog__id')
    )

    task = Sbacklog.objects.values(
        'id',
        'nombre',
        'usuario__first_name',
        'usuario__last_name',
        'n_horas',

templates/xp/actualizar_historia.html
{% extends 'base/base.html'%}

<html lang="en">
<head>
    <!DOCTYPE html>
    <meta charset="UTF-8">
    {% block title %}
        <title>Actualizar historia</title>
    {% endblock %}
</head>
<body>
    {% block content %}
         <div class="row justify-content-center">
          <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
              <div class="card-body p-0">
                  <div class="container">
                      <form method="POST">
                          {% csrf_token %}
                          <div class="form-group">
                              {{form.como_usuario.label }}
                              {{form.como_usuario }}
                          </div>
                          <div class="form-group">
                              {{ form.quiero.label}}
                              {{ form.quiero}}
                          </div>
                          <div class="form-group">
                              {{ form.para.label}}
                              {{ form.para}}
                          </div>
                          <div>
                             {{ form.id_xp }}
                          </div>
                          <div class="row">
                              <div class="col" align="center">
                                  <button type="submit" style="width:80%;" class="btn btn-primary">Guardar</button>
                              </div>
                              <div class="col" align="center">
                                  <button type="button" style="width:80%;" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                              </div>
                          </div>
                      </form>
                  </div>
              </div>
            </div>
          </div>
         </div>
    {% endblock %}
</body>
</html>

templates/xp/historia_usuario.html
{% extends 'base/base.html'%}
<html lang="en">
<head>
    <!DOCTYPE html>
    <meta charset="UTF-8">
    {% block title%}
        <title>Crear H.U</title>
    {% endblock%}
</head>
<body>

{% block content %}

 <script>
        function seleccionar(id, historia) {
            document.getElementById('id_historia').value = id;
            document.getElementById('textTarea').innerText = historia;
        }

        function eliminarHistoria(id, historia){
            document.getElementById('confirmar').innerHTML = '<a href="/xp/eliminar_historias/'+ id +'"  title="Eliminar historia" style="width:50%" class="btn btn-danger" data-target="modal" data-target="#confirmDeleteHistory"> Eliminar </a>';
            document.getElementById('texto').innerHTML = "Seguro que desea eliminar la historia de usuario <strong>"+ historia +"</strong>, todas las tareas perteneciente a ella se eliminarán "
        }
  </script>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col">
                 <strong class="card-title">Listado de historias de usuarios</strong>
            </div>
             <div class="col" align="right">
                    {% if historias %}
                        <a class="btn btn-outline-success" title="Finalizar e ir a detalles"  href="{% url 'xp:index-xp' id_pro %}">Finalizar</a>
                    {% endif %}
                    <button class="btn btn-outline-primary" data-toggle="modal" data-target="#ListTareas">Ver Tareas</button>
                    <button class="btn btn-success" data-toggle="modal" data-target="#myModal">Agregar Historia</button>
             </div>
        </div>

    </div>
    <div class="table-stats order-table ov-h">
        <table class="table table-sm table-hover ">
            <thead class="thead-dark">
                <tr>
                    <th>Usuario</th>
                    <th>Quiero</th>
                    <th>Para</th>
                    <th>Tareas</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% if historias %}
                    {% for h in historias %}
                        <tr>
                            <td>{{h.como_usuario }}</td>
                            <td>{{h.quiero }}</td>
                            <td>{{h.para}}</td>
                            <td>{{h.tareas}}</td>
                            <td>
                                 <button class="btn btn-sm btn-outline-success" title="Ingrese las tareas" data-toggle="modal" data-target="#myTareas" onclick="seleccionar('{{h.id}}','{{h.quiero}}')">
                                     Tarea
                                 </button>
                                <a href="{% url 'xp:ActualizarHistorias' h.id %}" title="Editar historia" class="btn btn-sm btn-outline-primary">Editar</a>
                                <!--
                                <a href="{% url 'xp:eliminar_historias' h.id %}" title="Eliminar historia" class="btn btn-sm btn-outline-danger" data-target="modal" data-target="#confirmDeleteHistory"> Eliminar </a>
                                -->
                                <button title="Eliminar historia" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#confirmDeleteHistory" onclick="eliminarHistoria('{{h.id}}','{{h.quiero}}')"> Eliminar </button>

                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</div>

<!-- The Modal tareas-->
  <div class="modal fade" id="myTareas">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">Creación de tareas</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">


            <div class="container">
                <div class="alert alert-info" role="info">
                    <h6 style="text-align:center;">
                        <font >Historia de Usuario</font>
                    </h6>
                    <h5 style="text-align:center">
                        <strong><span id="textTarea"></span></strong>
                    </h5>
                </div>
                <br>
                <form method="POST" action="/xp/CrearTareas/">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>
                            Descripción de la tarea
                        </label>
                        <input type="text" class="form-control" name="nombre" placeholder="Ingrese el nombre o descripción de la tarea" required>
                    </div>

                    <div class="form-group">
                        <label>
                            Número de días
                            <i class="fas fa-question-circle" title="El número máximo de horas por tareas es de 8" style="cursor:pointer"></i>
                        </label>
                        <input type="number" class="form-control" placeholder="Ingrese el número de días para la tarea" name="n_horas" required>
                    </div>

                    <div>
                        <input type="hidden" name="id_historia" id="id_historia">
                        <input type="hidden" name="get" value="False">
                        <input type="hidden" name="estado" value="False">
                    </div>

                    <div class="row">
                        <div class="col" align="center">
                            <button type="submit" style="width:80%;" class="btn btn-primary">Guardar</button>
                        </div>
                        <div class="col" align="center">
                            <button type="button" style="width:80%;" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
      </div>
    </div>
  </div>
<!-- end modal tareas -->

<!-- The Modal Historia -->
  <div class="modal fade" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">Historias de Usuarios</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
            <div class="container">
                <form method="POST" action="/xp/CrearHistorias/">
                    {% csrf_token %}
                    <div class="form-group">
                        {{form.como_usuario.label }}
                        {{form.como_usuario }}
                    </div>
                    <div class="form-group">
                        {{ form.quiero.label}}
                        {{ form.quiero}}
                    </div>
                    <div class="form-group">
                        {{ form.para.label}}
                        {{ form.para}}
                    </div>
                    <div>
                        <input type="hidden" name="id_xp" value={{ xp }}>
                        <input type="hidden" name="estado" value="False">
                        <input type="hidden" name="get" value="False">
                    </div>
                    <div class="row">
                        <div class="col" align="center">
                            <button type="submit" style="width:80%;" class="btn btn-primary">Guardar</button>
                        </div>
                        <div class="col" align="center">
                            <button type="button" style="width:80%;" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
      </div>
    </div>
  </div>
<!-- end modal -->

 <!-- The Modal ver tareas -->
<div class="modal fade" id="ListTareas">
    <div class="modal-dialog modal-xl">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title"><strong>Listado de Tareas</strong></h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">

          {% if tareas %}
                <div class="card">
                    <table class="table table-sm table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>HISTORIA DE USUARIO</th>
                                <th>TAREA</th>
                                <th>DURACION</th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for t in tareas%}
                                <tr>
                                    <td>{{ t.id_historia__quiero}}</td>
                                    <td>{{ t.nombre}}</td>
                                    <td>{{ t.n_horas}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}

            {% endif %}
        </div>
      </div>
    </div>
</div>


<!-- Modal confirmar eliminar historia -->
    <div class="modal fade" id="confirmDeleteHistory">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"><strong>Eliminar Historia de Usuario</strong></h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p id="texto">
                        Si, elimina esta historia de usuarios, tenga en cuenta que
                        se eliminaran las tareas que hacen parte de ella.
                    </p>
                </div>
                <div class="modal-footer">
                    <div class="container" align="center" id="confirmar"></div>
                </div>
            </div>
        </div>
    </div>
<!-- end modal delete history -->
{% endblock %}
</body>
</html>