apps/proyecto/urls.py
from django.conf.urls import url
from django.urls import path

from apps.proyecto.views import proyecto_crear, proyecto_list, index, estado, integrante, actualizarHistorias, index2, getTareas, getTareasDetalle, actualizarTarea
app_name = 'proyecto'

urlpatterns = [
   # path('index/', index, name='index' ),
    url(r'^nuevo$', proyecto_crear, name='crear_proyecto'), 
    url(r'^listar$', proyecto_list, name='listar_proyecto'),
    url(r'^index/(?P<id>\d+)/$', index, name='index'),
    url(r'^estado$', estado, name='estado'),
    url(r'^actualizarHistorias$', actualizarHistorias, name='actualizarHistorias'),
    url(r'^integrante$', integrante, name='integrante'),
    path('index2', index2, name='index2'),
    path('getTareas', getTareas, name='getTareas'),
    path('getTareasDetalle', getTareasDetalle, name='getTareasDetalle'),
    path('actualizarTarea', actualizarTarea, name='actualizarTarea'),
]

apps/scrum/urls.py
from django.conf.urls import url
from django.urls import path
from apps.scrum.views import scrum_list, scrum_crear, pbacklog_crear, pbacklog_list, historia_crear, update_pbacklog, eliminarPbacklog
from apps.scrum.views import sbacklog_estado, historia_list, sbacklog_crear, sbacklog_list, sprint, dailymeeting, sreview
from apps.scrum import views
app_name = 'scrum'

urlpatterns = [

    url(r'^scrum_crear$', scrum_crear, name='scrum_crear'),
    url(r'^scrum_list$', scrum_list, name='scrum_list'),
    url(r'^pbacklog_crear$', pbacklog_crear, name='pbacklog_crear'),
    url(r'^pbacklog_list$', pbacklog_list, name='pbacklog_list'),
    url(r'^historia_crear$', historia_crear, name='historia_crear'),
    url(r'^historia_list$', historia_list, name='historia_list'),
    url(r'^sbacklog_crear$', sbacklog_crear, name='sbacklog_crear'),
    url(r'^sbacklog_list$', sbacklog_list, name='sbacklog_list'),
    url(r'^sbacklog_estado$', sbacklog_estado, name='sbacklog_estado'),
    url(r'^sprint/(?P<id>\d+)/$', sprint, name='sprint'),
    path('dailymeeting', dailymeeting, name='dailymeeting'),
    path('sreview', sreview, name='sreview'),
    path('update_pbacklog', update_pbacklog, name='update_pbacklog'),
    path('eliminarPbacklog', eliminarPbacklog, name='eliminarPbacklog'),
    path('update_epica', views.update_epica, name='update_epica'),
    path('delete_epica', views.delete_epica, name='delete_epica'),
    path('update_historia', views.update_historia, name='update_historia'),
    path('delete_historia', views.delete_historia, name='delete_historia'),
    path('delete_tarea', views.delete_tarea, name='delete_tarea'),
    path('edit_epicas_sprint', views.edit_epica_sprint, name="edit_epicas_sprint"),
    path('listado_historias_sprint', views.listado_historias_sprint, name="listado_historias_sprint"),
    path('editar_historias_sprint', views.editar_historia_sprint, name="editar_historias_sprint"),
    path('eliminar_historia', views.eliminar_historia, name="eliminar_historia"),
    path('tabla_tareas_sprint', views.tabla_tareas_sprint, name="tabla_tareas_sprint"),
    path('add_tarea_sprint', views.add_tarea_sprint, name="add_tarea_sprint"),
    path('update_tarea_sprint', views.update_tarea_sprint, name="update_tarea_sprint"),
    path('delete_tarea_sprint', views.delete_tarea_sprint, name="delete_tarea_sprint"),

]

way/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('apps.usuarios.urls')),
    url(r'^admin/', admin.site.urls),
     #url(r'^base/', include ('templates.base.urls')),
    url(r'^usuarios/', include ('apps.usuarios.urls')),
    url(r'^proyecto/', include ('apps.proyecto.urls')),
    url(r'^scrum/', include ('apps.scrum.urls')),

    path('xp/',include('apps.xp.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='usuarios/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='usuarios/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='usuarios/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='usuarios/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

#configuracion de rutas para imagenes
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/proyecto/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.usuarios.models import Usuario
from django.utils import timezone


class Tipo_metodologia(models.Model):
    nombre = models.CharField(max_length=500)

    def __str__(self):
        return '{}'.format(self.nombre)


class Proyecto(models.Model):
    nombre = models.CharField(max_length = 500)
    fecha = models.DateTimeField(default=timezone.now)
    f_inicio = models.DateField(null = True, blank = True)
    f_fin = models.DateField(null = True, blank = True)
    id_metodologia = models.ForeignKey(Tipo_metodologia, null =True, blank = True, on_delete = models.CASCADE)
    usuario = models.ManyToManyField(User, through='ProUser')

    def __str__(self):
        return '{}'.format(self.nombre)
# Create your models here.


class Rol(models.Model):
    metodologia = models.ForeignKey(Tipo_metodologia, null=True, blank=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length= 300,null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.nombre)


class ProUser(models.Model):
    usuario = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    proyecto = models.ForeignKey(Proyecto, null=True, blank=True, on_delete=models.CASCADE)
    disponible = models.BooleanField(null=True, blank=True)
    horas = models.IntegerField(null=True, blank=True)
    rol = models.ForeignKey(Rol, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.proyecto)


# Create your models here.

apps/proyecto/forms.py
from django import forms
from apps.proyecto.models import Proyecto

class ProyectoForm(forms.ModelForm):

    class Meta:
        model = Proyecto

        fields = [
            'nombre',
            'f_inicio',
            'f_fin',
            'id_metodologia',
        ]

        labels = {
            'nombre': 'Nombre del proyecto',
            'f_inicio': 'Fecha de inicio',
            'f_fin': 'Fecha de fin',
            'id_metodologia':'Métodologia de desarrollo',
        }

        widgets = {
           'nombre': forms.TextInput(attrs={
               'class':'form-control',
               'required': 'required'
           }),

            'f_inicio': forms.DateInput(attrs={
                'class':'form-control',
                'type':'date',
                'required':'required'
            }),

            'f_fin': forms.DateInput(attrs={
                'class':'form-control',
                'type':'date',
                'required': 'required'
                 }),

            'id_metodologia': forms.TextInput(attrs={'class':'form-control'}),
            #'usuario': forms.HiddenInput(),
        }

apps/proyecto/views.py
from itertools import chain

from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.core import serializers
from django.db.models import Count, Q
from datetime import date

from django.template.loader import render_to_string

from apps.proyecto.models import Proyecto, Rol, ProUser, Tipo_metodologia
from apps.proyecto.forms import ProyectoForm
from apps.scrum.models import Scrum, Pbacklog, HistoriaUsuario, Sbacklog, Sprint, DailyMeeting

from apps.usuarios.models import User, Usuario
from apps.xp.models import XP

#Herramientas 
from herramientas.funciones import verificar_roles

import json


@login_required
def get_data(request, pro):
    return redirect('/proyecto/index/'+str(pro))


@login_required
def index(request, id):
    p = Proyecto.objects.filter(id=id)
    sprint = Sprint.objects.filter(estado=True, id_scrum__proyecto__id=p[0].id)
    sprint_to_confirm = Sprint.objects.filter(estado=False, confirmar=True, id_scrum__proyecto__id=p[0].id)
    if sprint_to_confirm:
        id_sprint_cf = sprint_to_confirm[0].id
        alcanzados = Pbacklog.objects.filter(estado=True, id_scrum__proyecto__id=id, sprint__id=id_sprint_cf)
    else:
        alcanzados = ""

    if sprint:
        id_sprint = sprint[0].id
        
        backlog = Pbacklog.objects.filter(sprint__id=id_sprint, estado=False).annotate(
            historias=Count('historiausuario__id')
        )

        historic = HistoriaUsuario.objects.filter(id_pbacklog__sprint__id=id_sprint)
        tareas = Sbacklog.objects.filter(id_historia__id_pbacklog__sprint__id=id_sprint, get=False)
        hechas = Sbacklog.objects.filter(id_historia__id_pbacklog__sprint__id=id_sprint, estado=True)
        haciendo = Sbacklog.objects.values('id','nombre', 'usuario__first_name','usuario__last_name','usuario__id').filter(
            id_historia__id_pbacklog__sprint__id=id_sprint,
            get=True,
            estado=False
        )
        info = Sprint.objects.get(estado=True, id_scrum__proyecto__id=p[0].id)
        var = info.f_fin - date.today()
    else:
        backlog = ""
        historic = ""
        tareas = ""
        hechas = ""
        haciendo = ""
        info = ""
        var = ""
        sprint = Sprint.objects.filter(estado=False, confirmar=True, id_scrum__proyecto__id=p[0].id)
        if sprint:
            id_sprint = sprint[0].id
        else:
            id_sprint =""


    integrantes = ProUser.objects.values(
        'usuario__username',
        'usuario__first_name',
        'usuario__last_name',
        'rol__nombre',
        'horas'
    ).filter(proyecto=id)
    
    rol = ProUser.objects.values('rol__nombre').filter(proyecto=id,usuario=request.user.pk)
    print('rol del actualmente conectado',rol)

    #listado de requisitos terminados y sin terminar
    f = Pbacklog.objects.filter(estado=False, id_scrum=22)

    r = Pbacklog.objects.filter(estado=True, id_scrum=22)

    #la siguiente consulta obtendra la lista de cada daylimeeting registrado hasta el momento en que se realiza la consulta.
    meetingsday = DailyMeeting.objects.values('usuario__first_name','usuario__last_name','ayer','hoy','problemas').filter(
        sprint__estado=True, sprint__id_scrum__proyecto__id=id
    )

    resumen = resumenScrum(id)
    resumen_requisitos = resumen['requisitos']
    resumen_proyecto = resumen['proyecto']
    resumen_integrantes = resumen['integrantes']
    resumen_sprints = resumen['sprint']
    datos1 = resumen_sprints['datos1']
    datos2 = resumen_sprints['datos2']
    resumen_tareas = resumen['tareas']
    resumen_daily = resumen['daily']

    contexto = {'pbacklog': backlog,
                'historia': historic,
                'tareas': tareas,
                'proyecto': p,
                'idIndex': id,
                'haciendo': haciendo,
                'hechas': hechas,
                'integrantes': integrantes,
                'sprint': id_sprint,
                'info': info,
                'var': var,
                'Rterminados':r,
                'RsinTerminar':f,
                'alcanzados': alcanzados,
                'meetingsday': meetingsday,
                'rol':rol,
                'resumen_proyecto':resumen_proyecto,
                'resumen_requisitos':resumen_requisitos,
                'resumen_integrantes':resumen_integrantes,
                'resumen_sprints_datos1':datos1,
                'resumen_sprints_datos2':datos2,
                'resumen_tareas':resumen_tareas,
                'resumen_daily':resumen_daily
    }

    return render(request, 'proyecto/index.html', contexto)


@login_required
def requisitos():
    t = Pbacklog.objects.filter(estado=False, id_scrum=22)
    r = Pbacklog.objects.filter(estado=True, id_scrum=22)
    s = t | r
    pass


@login_required
def index2(request):
    id = request.session['proyectoIndex']
    return index(request,id)


@login_required
def proyecto_crear(request):
    usuario = request.user.pk
    if request.method == 'POST':
        metodologia = verificar_metodologia(request.POST["id_metodologia"])
        nombre = request.POST["nombre"]
        f_inicio = request.POST["f_inicio"]
        f_fin = request.POST["f_fin"]
        # form = ProyectoForm(request.POST)        
  
        proyecto = Proyecto.objects.create(nombre=nombre, f_inicio=f_inicio, f_fin=f_fin, id_metodologia = metodologia)

        # guardo el proyecto
        proyecto.save()
        
        # get id user from POST method
        u = User.objects.get(id=usuario)
        midle = ProUser(usuario=u, proyecto=proyecto, horas=40)
        midle.save()
        # realizo una consulta para saber la metodologia elegida
      
        if metodologia.nombre == "SCRUM":  # pregunta si la metodologia es scrum
            b = Scrum.objects.create(proyecto=proyecto)  # crear el registro en scrum con el id del proyecto.
            rol = verificar_roles("Product Owner", metodologia)
            ProUser.objects.filter(id=midle.id).update(rol=rol.id)
            request.session['scrum'] = b.id
            return redirect('scrum:pbacklog_crear')
        elif metodologia.nombre == 'XP':
            x = XP.objects.create(proyecto=proyecto)
            rol = verificar_roles('Manager', metodologia)
            ProUser.objects.filter(id=midle.id).update(rol=rol.id)
            request.session['xp']=x.id
            return redirect('xp:CrearHistorias')
        else:
            return redirect('usuarios:index')
    else:
        form = ProyectoForm()
    return render(request, 'proyecto/proyecto_form.html', {'form': form, 'usuario': usuario})

def verificar_metodologia(metodologia):
    try:
        valor = Tipo_metodologia.objects.get(nombre=metodologia)
        return valor
    except:
        valor = Tipo_metodologia.objects.create(nombre=metodologia)
        return valor
    

@login_required
def proyecto_list(request):
    proyecto = Proyecto.objects.all().order_by('id')
    contexto = {'proyecto': proyecto}
    return render(request, 'proyecto/proyecto_list.html', contexto)


@login_required
def estado(request):
    if request.method == 'POST':
        print('datos del formulario',request.POST)
        id = request.POST['id']

        #idIndex = request.POST['idIndex']  # el idIndex es el id que le pertenece al proyecto
        id_sprint = request.POST['sprint']

        idUser = request.user.pk
        Sbacklog.objects.filter(id=id).update(usuario=idUser, get=True)
        # Sbacklog.objects.filter(id=id).update(get=True)
        tareas = Sbacklog.objects.filter(id_historia__id_pbacklog__sprint__id=id_sprint, get=False)
        hechas = Sbacklog.objects.filter(id_historia__id_pbacklog__sprint__id=id_sprint, estado=True)
        haciendo = Sbacklog.objects.values('id','nombre', 'usuario__first_name','usuario__last_name','usuario__id').filter(
            id_historia__id_pbacklog__sprint__id=id_sprint,
            get=True,
            estado=False
        )
        contexto = {
            'pendientes': tareas,
            'hechas':hechas,
             'haciendo':haciendo,
            'user_pk':idUser,
            'sprint':id_sprint,
            'idIndex':request.POST['idIndex']
        }

    datos = {'listTareas': render_to_string('clean/tablero_scrum.html',contexto)}

    return JsonResponse(datos)


@login_required
def tareas(request):
    usuario = request.session['id_user']
    if request.method == 'POST':
        idUser = request.session['id_user']
        id = request.POST['id']
        idIndex = request.POST['idIndex']  # el idIndex es el id que le pertenece al proyecto
        Sbacklog.objects.filter(id=id).update(usuario=idUser)
        return index(request, idIndex)
    return render(request, 'usuarios/tareas.html', {'usuario': usuario})


@login_required
def integrante(request):
    print('datos enviados del integrante', request.POST)
    if request.method == "POST":

        email = request.POST['email']
        try:
            usuario = User.objects.get(email=email)
        except:
            usuario = ""
        pro = request.POST['idIndex']

        if usuario != "":
            validar = ProUser.objects.filter(usuario=usuario.id, proyecto=pro)
            if validar:
                pass
            else:
                r = request.POST['rol']
                rol = Rol.objects.get(nombre=r)
                horas = request.POST['horas']

                proyecto = Proyecto.objects.get(id=pro)
                guardar = ProUser(usuario=usuario, proyecto=proyecto, disponible=True, rol=rol, horas=horas)
                guardar.save()
    return JsonResponse({'datos':'ready'})


@login_required
def actualizarHistorias(request):
    if request.method == 'GET':
        id = request.GET['id']
        d = HistoriaUsuario.objects.filter(id_pbacklog=id).annotate(
            tareas=Count('sbacklog__id'),

templates/proyecto/proyecto_form.html
{% extends 'base/base.html'%}
{% load static %}
{% block content %}
{% block title %}
        <title>Crear Proyecto</title>
{% endblock %}
{% block extra_links%}
<link href="{% static 'estilos/proyecto/form.css' %}" rel="stylesheet">
{% endblock %}

<div class="container">
        <div class="card">
                <div class="text-center">
                        <strong>
                                <h2>Crear Proyecto</h2>
                        </strong>
                </div>
                <br>
                <div class="card-body">
                        <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                        {{ form.nombre.label }}
                                        {{ form.nombre.errors }}
                                        {{ form.nombre }}
                                </div>

                                <div class="form-group">
                                        <div class="row">
                                                <div class="form-group col-sm-6">
                                                        {{ form.f_inicio.label }}
                                                        {{ forms.f_inicio.errors }}
                                                        {{ form.f_inicio }}
                                                </div>
                                                <div class="form-group col-sm-6">
                                                        {{ form.f_fin.label }}
                                                        {{ form.f_fin.errors }}
                                                        {{ form.f_fin }}
                                                </div>
                                        </div>
                                </div>


                                <div class="form-group">
                                        <label>Metodología de desarrollo</label>
                                        {{ form.id_metodologia.errors }}
                                        <select name="id_metodologia" class="form-control">
                                                <option value="SCRUM" selected>SCRUM</option>
                                                <option value="XP">XP</option>
                                        </select>
                                </div>

                                <div class="row" aling="center">
                                        <div class="col" aling="right">
                                                <button class="btn btn-primary" style="width:60%" type="submit"> Guardar </button>
                                        </div>
                                        <div class="col" aling="center">
                                                <a class="btn btn-danger" style="width:60%" href="/usuarios/index">Cancelar</a>
                                        </div>
                                </div>
                        </form>
                </div>
        </div>
</div>
<hr>

<script>
        $(document).on('input','#id_f_inicio',function(e){
                var fecha_inicio = $(this).val();
                document.getElementById('id_f_fin').min = fecha_inicio;
        });

        $(document).on('input','#id_f_fin',function(e){
                var fecha_inicio = document.getElementById('id_f_inicio').value;
                if (fecha_inicio == ""){
                        alert('Primero ingrese la fecha de inicio');
                        fecha_fin = document.getElementById('id_f_fin').value = "";
                }
                
        });
</script>

{% endblock %}

templates/proyecto/proyecto_list.html
{% extends 'base/base.html' %}
{% block content %}

<table class="table">
    <thead>
        <tr>
            <td>#</td>
            <td>Fecha </td>
            <td>Nombre</td>
            <td>Fecha de inicio</td>
            <td>Fecha de fin</td>
            <td>Metodologia de desarrollo</td>
            <td>Opcion</td>
        </tr>
    </thead>
    <tbody>
        {% if proyecto %}
        
            {% for p in proyecto %}
                <tr>
                    <td>{{ p.id }}</td>
                    <td>{{ p.fecha }}</td>
                    <td>{{ p.nombre }} </td>
                    
                    <td>{{ p.f_inicio }}</td>
                    <td>{{ p.f_fin }}</td>
                    <td>{{ p.id_metodologia}}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'scrum:scrum_crear' %}">scrum</a>
                    </td>
            
                </tr>
            {% endfor %}
    
        {% else %}
            <h1>No hay registros de proyectos</h1>
        
        {% endif %}
    </tbody>
</table>
{% endblock %}