apps/proyecto/urls.py
from django.conf.urls import url
from django.urls import path

from apps.proyecto.views import proyecto_crear, proyecto_list, index, estado, integrante, actualizarHistorias, index2, getTareas, getTareasDetalle, actualizarTarea
app_name = 'proyecto'

urlpatterns = [
   # path('index/', index, name='index' ),
    url(r'^nuevo$', proyecto_crear, name='crear_proyecto'), 
    url(r'^listar$', proyecto_list, name='listar_proyecto'),
    url(r'^index/(?P<id>\d+)/$', index, name='index'),
    url(r'^estado$', estado, name='estado'),
    url(r'^actualizarHistorias$', actualizarHistorias, name='actualizarHistorias'),
    url(r'^integrante$', integrante, name='integrante'),
    path('index2', index2, name='index2'),
    path('getTareas', getTareas, name='getTareas'),
    path('getTareasDetalle', getTareasDetalle, name='getTareasDetalle'),
    path('actualizarTarea', actualizarTarea, name='actualizarTarea'),
]

apps/usuarios/urls.py
from django.conf.urls import url
from django.urls import path
from apps.usuarios.views import register,  index, logout, perfil, tareas, confirmar, getTareas, getTareasHechas, Login

app_name = 'usuarios'

urlpatterns = [
    #path('index', index, name='index'),
    url(r'^register$', register, name='register'),
    #url(r'^login$', login, name='login'),
    url(r'^index$', index, name='index'),

    url(r'^logout$', logout, name='logout'),
    url(r'^perfil$', perfil, name='perfil'),
    url(r'^tareas$', tareas, name='tareas'),
    url(r'^confirmar$', confirmar, name='confirmar'),
    path('getTareas', getTareas, name='getTareas'),
    path('getTareasHechas', getTareasHechas, name='getTareasHechas'),
    path('login', Login.as_view(), name='login'),
    path('', Login.as_view(), name='login'),

]

apps/xp/urls.py
from django.conf.urls import url
from django.urls import path
from apps.xp.views import CrearHistorias, CrearTareas, ActualizarHistorias, eliminarHistoria, index, crearCiclo, agregar_integrantes, obtener
from apps.xp import views
app_name = 'xp'

urlpatterns = [
    path('CrearHistorias/', CrearHistorias.as_view(), name='CrearHistorias'),
    path('CrearTareas/', CrearTareas.as_view(), name='CrearTareas'),
    path('ActualizarHistorias/<int:pk>', ActualizarHistorias.as_view(), name='ActualizarHistorias'),
    path('eliminar_historias/<int:id>', eliminarHistoria, name='eliminar_historias'),
    path('index-xp/<int:id>', index, name='index-xp'),
    path('crearCiclo', crearCiclo, name='crearCiclo'),
    path('agregar_integrantes', agregar_integrantes, name="agregar_integrantes"),
    path('obtener', obtener, name='obtener'),
    path('confirmar', views.confirmar, name='confirmar'),
    path('update_history', views.update_history, name='update_history'),
    path('show_crear_ciclo', views.show_crear_ciclo, name='show_crear_ciclo'),
    path('add_history_ciclo', views.add_history_ciclo, name='add_history_ciclo'),
    path('update_history_ciclo', views.update_history_ciclo, name='update_history_ciclo'),

]

way/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('apps.usuarios.urls')),
    url(r'^admin/', admin.site.urls),
     #url(r'^base/', include ('templates.base.urls')),
    url(r'^usuarios/', include ('apps.usuarios.urls')),
    url(r'^proyecto/', include ('apps.proyecto.urls')),
    url(r'^scrum/', include ('apps.scrum.urls')),

    path('xp/',include('apps.xp.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='usuarios/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='usuarios/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='usuarios/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='usuarios/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

#configuracion de rutas para imagenes
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


class Usuario(models.Model):
    celular = models.CharField(max_length=300, blank=True, null=True)
    id_user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='photos', null=True, blank=True)
    #photo = models.ImageField(null=True, blank=True)
# Create your models here.

apps/usuarios/views.py
'''
    repositorio de github donde se encuntra el tutorial para cambiar la contraseña
    https://github.com/CoreyMSchafer/code_snippets/tree/master/Django_Blog/12-Password-Reset/django_project
'''


import json

from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as do_login, logout as do_logout
from django.urls import reverse_lazy, reverse
from django.views.generic import FormView
from django.utils.decorators import method_decorator #decorador que se utiliza para aumentar la seguridad
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import login

from apps.usuarios.forms import RegistroForm, UsuarioForm, LoginForm
from apps.scrum.models import HistoriaUsuario, Pbacklog, Sbacklog, Scrum, Sprint
from django.db.models import Count, Q, Sum
from apps.usuarios.models import User, Usuario
from apps.proyecto.models import Proyecto



@login_required
def index(request):

    fotoPerfil(request)

    id = request.user.pk
    requisitos = Count('scrum__pbacklog__id', filter=Q(usuario=id))
    rcompletados = Count('scrum__pbacklog__id', filter=Q(scrum__pbacklog__confirmar=True))

    # proyecto con scrum
    '''
    p = Proyecto.objects.values(
        'nombre',
        'id_metodologia__nombre',
        'id'
    ).filter(usuario=id, id_metodologia__nombre='SCRUM').annotate(
        requisitos=requisitos,
        rcompletados=rcompletados,
        num=((rcompletados * 100)/requisitos)
    )
    '''
    p = Proyecto.objects.values(
        'nombre',
        'id_metodologia__nombre',
        'id'
    ).filter(usuario=id, id_metodologia__nombre='SCRUM').annotate(
        requisitos=requisitos,
        rcompletados=rcompletados
    )

    rpendientes_xp = Count('scrum__pbacklog__id', filter=Q(usuario=id))
    rcompletos_xp = Count('scrum__pbacklog__id', filter=Q(scrum__pbacklog__confirmar=True))

    #proyecto con xp
    xp_p = Proyecto.objects.values(
        'nombre',
        'id_metodologia__nombre',
        'id'
    ).filter(usuario=id, id_metodologia__nombre='XP').annotate(
        rpendientes=rpendientes_xp,
        rcompletados=rcompletos_xp
    )


    contexto = {
        'proyecto': p,
        'xp_p':xp_p
    }

    return render(request, 'usuarios/index.html', contexto)


def fotoPerfil(request):
    try:
        usuario = Usuario.objects.get(id_user=request.user.pk)
        request.session['photo'] =  usuario.photo.url
    except:
        print('No tiene foto')


class Login(FormView):
    '''
        guia para la creacion de login
         https://www.youtube.com/watch?v=Twv0Ok9MerI
    '''

    template_name = 'usuarios/login2.html'
    form_class = LoginForm
    success_url = reverse_lazy('usuarios:index')

    #vamos a importar un decorador para un metodo, el cual nos ayudara a aumentar la seguridad
    #son dos never chache la cual evitara a que se guarden las credenciales en cache y crops.. que brinda seguridad a bulnerabilidades mas conocidas

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)

    #dispatch en vistas basadas en clases es el primero que se ejecuta, este metodo se encarga de redirigir las peticiones es decir si es POST la envia al metodo POST y si es GET la envia al GET
    def dispatch(self, request, *args, **kwargs):

        if request.user.is_authenticated:

            #return HttpResponseRedirect(self.get_success_url()) #el metodo get_success_url lo que hace es redireccionarnos a la direccion que especificamos arriba en este caso seria index
            return HttpResponseRedirect(self.get_success_url()) #el metodo get_success_url lo que hace es redireccionarnos a la direccion que especificamos arriba en este caso seria index
        else:
            return super(Login,self).dispatch(request, *args, **kwargs)

    def form_valid(self, form): # validamos el formulario de que se utiliza en la vista
        login(self.request, form.get_user())
        return super(Login,self).form_valid(form)


def logout(request):
    # finalizamos la sesion
    do_logout(request) #cierra todas las sesiones que se encuentren en el navegador, es decir borra los registros de la variblea request.session
    # Redireccionamos al login
    return redirect('usuarios:login')


def registrarusario(self):
    usuario = User(first_name=self.data['first_name'],
                   last_name=self.data['last_name'],
                   username=self.data['username'],
                   email=self.data['email'],
                   password=self.data['password1'])

    usuario.save()


def register(request):
    if request.method == "POST":
        print(request.POST, request.FILES)

        form = RegistroForm(request.POST, request.FILES)
        
        if form.is_valid():

            nomrbe = form.cleaned_data['first_name']
            apellido = form.cleaned_data['last_name']
            usuario = form.cleaned_data['username']
            correo = form.cleaned_data['email']
            passwd = form.cleaned_data['password']

            usercomplement = Usuario()
            usercomplement.photo = request.FILES.get('photo')
            usercomplement.celular = request.POST['celular']

            try:
                datos = User.objects.create_user(first_name=nomrbe, last_name=apellido, username=usuario, email=correo,
                                                 password=passwd)
                datos.save()

                ''''
                if request.POST['celular'] != "":
                    cell = Usuario.objects.create(celular=request.POST['celular'], id_user=datos, photo=photo)
                    cell.save()
                '''
                usercomplement.id_user = datos
                usercomplement.save()

                return redirect('usuarios:login')
            except Exception as error:
                print("error", error)
        else:
            print('ocurrio un error al registrar el usuario',form.errors)
           
    else:
        form = RegistroForm

    return render(request, "usuarios/register.html", {'form':form})


def update(request):
    pass


@login_required
def perfil(request):
    usuario = User.objects.values('first_name','last_name', 'email', 'usuario__celular', 'username').filter(id=request.user.pk)
    proyecto = Proyecto.objects.filter(usuario=request.user.pk)
    contexto = {'contexto': usuario, 'proyecto': proyecto}
    return render(request, 'usuarios/perfil.html', contexto)


@login_required
def tareas(request):
    id = request.user.pk

    requisitos = Count('scrum__pbacklog__historiausuario__sbacklog__id',
                       filter=Q(scrum__pbacklog__historiausuario__sbacklog__estado=False,
                                scrum__pbacklog__historiausuario__sbacklog__get=True,
                                scrum__pbacklog__historiausuario__sbacklog__usuario=id
                                ))

    rcompletados = Count('scrum__pbacklog__id', filter=Q(scrum__pbacklog__estado=True))
    p = Proyecto.objects.values(
        'nombre',
        'id'
    ).filter(usuario=id).annotate(
        requisitos=requisitos,
        rcompletados=rcompletados
    )
    #contexto = {'tareas': tarea, 'proyecto': proyecto, 'hechas': hechas}
    contexto = {'proyecto': p}
    return render(request, 'usuarios/tareas.html', contexto)


@login_required
def confirmar(request):
    id = request.POST['id']
    Sbacklog.objects.filter(id=id).update(estado=True)

    # Consulto la historia de usuario
    h = HistoriaUsuario.objects.filter(sbacklog__id=id)
    pb = Pbacklog.objects.get(historiausuario__sbacklog__id=id)

    # calculo si las tareas perteneciente a la misma historia de usuarios q ya estan completadas
    a = Sbacklog.objects.filter(id_historia=h[0].id).count()
    b = Sbacklog.objects.filter(id_historia=h[0].id, estado=True).count()

    # obtengo el procentaje de tareas cumplidas y dependiendo del resultado actualizo el modelo HistoriaUsuario
    x = (b * 100) / a
    if x == 100:
        HistoriaUsuario.objects.filter(id=h[0].id).update(estado=True)

    # si todas las historias de usuarios de un requisito ya estan completadas le cambio el estado a verdadero
    h1 = HistoriaUsuario.objects.filter(id_pbacklog=pb.id).count()
    h2 = HistoriaUsuario.objects.filter(id_pbacklog=pb.id, estado=True).count()

    s = (h2 * 100) / h1
    if s == 100:
        Pbacklog.objects.filter(id=pb.id).update(estado=True)

    #si todos los requisitps seleccionados para un sprint ya estan cumplidos, desactivo el sprint par poder crear uno nuevo
    #par amayor presision utilizo el id de scrum para poder identificar exactamente el sprint perteneciente al proyecto
    idscrum = Scrum.objects.get(pbacklog__id=pb.id)
    idsprint = Sprint.objects.get(id_scrum=idscrum.id, estado=True)
    idpb = Pbacklog.objects.filter(sprint=idsprint).count()
    idpb_activo = Pbacklog.objects.filter(sprint=idsprint, estado=True).count()
    resultado = (idpb_activo * 100)/idpb
    if resultado == 100:
        Sprint.objects.filter(id=idsprint.id).update(estado=False, confirmar=True)
        #la variable confirmar en sprint sirve para que despues de terminado el sprint, se pueda avilitar el sprint review
    return JsonResponse({'datos':'guardados'})


@login_required
def getTareas(request):
    if request.method == 'GET':
        id = request.GET['id']
        usuario = request.user.pk
        d = Sbacklog.objects.filter(id_historia__id_pbacklog__id_scrum__proyecto__id=id, usuario=usuario, get=True, estado=False)
        datos = serializers.serialize('json', d)
    else:
        print("hubo algun error...")
    return HttpResponse(datos, content_type='application/json')


@login_required

templates/usuarios/index.html
{% extends 'base/base.html'%}
{% load static %}


{% block extra_links %}
    <link href="{% static 'estilos/usuario/index_usuario.css' %}" rel="stylesheet">
    <script src=""></script>
{% endblock %}
{% block content %}

   
    <!-- Begin Page Content --><!--Contenido de la pagina-->
    <div class="container-fluid">          
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
           <h1 class="h3 mb-0 text-gray-800">Proyectos</h1>
        </div>          
        <!-- Content Row -->
       
        <div class="row">
            <!-- Crear proyecto -->
              <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left shadow h-100 py-2">
                  <div class="card-body">
                    <div class="row no-gutters align-items-center">
                      <div class="col mr-2">
                        <div class="text-l font-weight-bold text-primary text-uppercase mb-1">Crear proyecto</div>
                      </div>
                      <div class="col-auto">
                        <a href="/proyecto/nuevo" class="btn btn-circle">
                          <i class="fas fa-plus fa-2x text-black-300"></i>
                        </a>
                      </div>
                    </div>
                  </div>
                    </div>
                </div>            

            <!-- Listado de proyectos con XP -->
          {% if xp_p %}
            {% for p in xp_p %}
                <!-- Ejemplo de proyecto 1-->
                <div class="col-xl-3 col-md-6 mb-4">
                    <a href="{% url 'xp:index-xp' p.id %}" style="text-decoration: none">
                    <div class="card border-left-info shadow h-100 py-2">
                        <div class="card-body"  >
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">

                                    <div class="text-s font-weight-bold text-info text-uppercase mb-1">{{ p.nombre }}</div>
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-auto">
                                            <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">0%</div>
                                            </div>
                                            <div class="col">
                                              <div class="progress progress-sm mr-2">
                                                <div class="progress-bar bg-info" role="progressbar" style="width: 0%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div>
                                        <hr>
                                        <table>
                                            <tbody>
                                                <tr>
                                                    <td >
                                                        <span class="font-small-3">R. Pendientes:</span>
                                                    </td>
                                                    <td class="pl-3">
                                                       <span>19</span>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>R. Terminados:</td>
                                                    <td class="pl-3">19</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <hr>
                                        <div class="text-center" >
                                            <strong class="text-success">{{ p.id_metodologia__nombre}}</strong>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    </a>
                </div>


          {% endfor %}

            <!-- Listado de proyecctos con SCRUM -->
        {% endif %}
             {% if proyecto %}
            {% for p in proyecto %}
                <!-- Ejemplo de proyecto 1-->
                <div class="col-xl-3 col-md-6 mb-4">
                    <a href="{% url 'proyecto:index' p.id %}" style="text-decoration: none">
                    <div class="card border-left-info shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">

                                    <div class="text-s font-weight-bold text-info text-uppercase mb-1">{{ p.nombre }}</div>
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-auto">
                                            <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{p.num}}%</div>
                                            </div>
                                            <div class="col">
                                              <div class="progress progress-sm mr-2">
                                                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: {{p.num}}%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>   
                                            </div>
                                        </div>
                                    </div>
                                    <hr>
                                    <table>
                                        <tbody>
                                            <tr>
                                                <td>R. Pendientes:</td>
                                                <td class="pl-3">
                                                    <span>{{p.requisitos}}</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <span>
                                                        R. terminados:
                                                    </span>
                                                </td>
                                                <td class="pl-3">
                                                    <span>
                                                        {{p.rcompletados}}
                                                    </span>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>                                      
                                    <hr>
                                    <div class="text-center">
                                        <strong class="text-success">{{ p.id_metodologia__nombre}}</strong>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    </a>
                </div>
          {% endfor %}
        {% endif %}
      </div>
        
    </div>
{% endblock %}

 <!-- Aqui se agregaran la listas de los proyecctos en la barra lateral -->
        {% block listProyecto %}

        {% endblock %}

templates/usuarios/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
      {% load static %}
    <meta charset="UTF-8">
    <title>Cambio completado</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
</head>
<body class="bg-gradient-primary">
    {% block content %}
      <div class="container">
        <!-- Outer Row -->
            <div class="row justify-content-center">

              <div class="col-xl-5 col-lg-15 col-md-9">

                    <div class="card o-hidden border-0 shadow-lg my-5">
                      <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row justify-content-center">
                            <div class="content-section">
                                <form method="POST">
                                    {% csrf_token %}
                                    <fieldset class="form-group">
                                        <legend class="border-bottom mb-4">Reset Password</legend>
                                        {{ form }}
                                    </fieldset>
                                    <div class="form-group">
                                        <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                      </div>
                    </div>
              </div>
            </div>
      </div>
    {% endblock content %}
</body>
</html>

templates/usuarios/tareas.html
{% extends 'base/base.html' %}
{% block content %}

    <html lang="en">
    <head>
        <!DOCTYPE html>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
        <!-- Begin Page Content -->
                <div class="container-fluid">

                  <!-- Page Heading -->
                  <h1 class="h3 mb-4 text-gray-800"><strong>TUS TAREAS</strong></h1>
                  <hr class="sidebar-divider">

                    {% if proyecto %}
                      <div class="row">

                            {% for p in proyecto %}
                                <div class="col-xl-3 col-md-6 mb-4" onclick="getTareas({{ p.id }})" style="cursor: pointer">
                                  <div class="card border-left-warning shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                          <div class="col mr-2">
                                            <div class="h6 font-weight-bold text-primary text-uppercase mb-1">{{p.nombre}}</div>
                                            <div class="h7 mb-0 font-weight-bold text-gray-800"> Sus tareas: {{p.requisitos}}</div>
                                          </div>
                                        </div>
                                    </div>
                                  </div>
                                </div>
                            {% endfor %}

                      </div>

                      <hr class="sidebar-divider">

                      <div class="row">

                          <div class="col-6">
                              <div class="text-center">
                                  <span><strong>HACIENDO</strong></span>
                              </div>
                              <div class="col">
                                  <div class="row">
                                      <div class="col"  id="listTareas">

                                      </div>
                                  </div>
                              </div>
                          </div>

                          <div class="col-6">
                              <div class="text-center">
                                  <span class="text-center"><strong>HECHAS</strong></span>
                              </div>
                              <div class="col">
                                  <div class="row">
                                      <div class="col" id="hechas">

                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                    {% else %}
                          <span><strong>Aun no tienes tareas</strong></span>
                    {% endif %}

                </div>
                <!-- /.container-fluid -->
    </body>
    </html>
<script>
    function getTareas(id){
        //alert(id)
        var dato = {'id':id};
        var url = "{% url 'usuarios:getTareas' %}";
         $.get(url, dato, function(json){
            if(json != ""){
                 console.log(json);
                  var html = "";
                    for(var i = 0; i < json.length; i++){
                        html += '<div class="card border-left-info shadow h-100 py-2">'+
                                      '<div class="card-body">'+
                                        '<div class="row">'+
                                          '<div class="col-10">'+
                                            '<div class="h7 mb-0 font-weight-bold text-gray-800">'+
                                             json[i].fields.nombre+
                                            '</div>'+
                                          '</div>'+
                                          '<div class="col-2 text-right">'+

                                                '<form method="post" action="{% url 'usuarios:confirmar' %}" >'+
                                                     '{% csrf_token %}'+
                                                     '<input type="hidden" value='+ json[i].pk +' name="id">'+
                                                     '<button type="submit" class="btn btn-primary">OK</button>'+
                                                '</form>'+
                                          '</div>'+
                                        '</div>'+
                                      '</div>'+
                                    '</div>'+'<br>'
                    } 

                    $('#listTareas').html(html);
            }else{
                $('#listTareas').html("Notiene tareas disponibles");
            }
        });

        url2 = "{% url 'usuarios:getTareasHechas' %}";
        $.get(url2, dato, function(hechas){
            console.log(hechas);
            if(hechas != ""){
                console.log(hechas);
                var html = "";
                for(var i = 0; i < hechas.length; i++){
                    html += '<div class="card border-left-success">'+
                            '<div class="card-header">'+
                                hechas[i].fields.nombre+
                            '</div>'+
                        '</div>'+
                        '<br>'
                }
                $('#hechas').html(html);
            } else{
                $('#hechas').html("Aun no ha culminado ninguna tarea");
            }
        });
    }
</script>
{% endblock %}