apps/scrum/urls.py
from django.conf.urls import url
from django.urls import path
from apps.scrum.views import scrum_list, scrum_crear, pbacklog_crear, pbacklog_list, historia_crear, update_pbacklog, eliminarPbacklog
from apps.scrum.views import sbacklog_estado, historia_list, sbacklog_crear, sbacklog_list, sprint, dailymeeting, sreview
from apps.scrum import views
app_name = 'scrum'

urlpatterns = [

    url(r'^scrum_crear$', scrum_crear, name='scrum_crear'),
    url(r'^scrum_list$', scrum_list, name='scrum_list'),
    url(r'^pbacklog_crear$', pbacklog_crear, name='pbacklog_crear'),
    url(r'^pbacklog_list$', pbacklog_list, name='pbacklog_list'),
    url(r'^historia_crear$', historia_crear, name='historia_crear'),
    url(r'^historia_list$', historia_list, name='historia_list'),
    url(r'^sbacklog_crear$', sbacklog_crear, name='sbacklog_crear'),
    url(r'^sbacklog_list$', sbacklog_list, name='sbacklog_list'),
    url(r'^sbacklog_estado$', sbacklog_estado, name='sbacklog_estado'),
    url(r'^sprint/(?P<id>\d+)/$', sprint, name='sprint'),
    path('dailymeeting', dailymeeting, name='dailymeeting'),
    path('sreview', sreview, name='sreview'),
    path('update_pbacklog', update_pbacklog, name='update_pbacklog'),
    path('eliminarPbacklog', eliminarPbacklog, name='eliminarPbacklog'),
    path('update_epica', views.update_epica, name='update_epica'),
    path('delete_epica', views.delete_epica, name='delete_epica'),
    path('update_historia', views.update_historia, name='update_historia'),
    path('delete_historia', views.delete_historia, name='delete_historia'),
    path('delete_tarea', views.delete_tarea, name='delete_tarea'),
    path('edit_epicas_sprint', views.edit_epica_sprint, name="edit_epicas_sprint"),
    path('listado_historias_sprint', views.listado_historias_sprint, name="listado_historias_sprint"),
    path('editar_historias_sprint', views.editar_historia_sprint, name="editar_historias_sprint"),
    path('eliminar_historia', views.eliminar_historia, name="eliminar_historia"),
    path('tabla_tareas_sprint', views.tabla_tareas_sprint, name="tabla_tareas_sprint"),
    path('add_tarea_sprint', views.add_tarea_sprint, name="add_tarea_sprint"),
    path('update_tarea_sprint', views.update_tarea_sprint, name="update_tarea_sprint"),
    path('delete_tarea_sprint', views.delete_tarea_sprint, name="delete_tarea_sprint"),

]

apps/usuarios/urls.py
from django.conf.urls import url
from django.urls import path
from apps.usuarios.views import register,  index, logout, perfil, tareas, confirmar, getTareas, getTareasHechas, Login

app_name = 'usuarios'

urlpatterns = [
    #path('index', index, name='index'),
    url(r'^register$', register, name='register'),
    #url(r'^login$', login, name='login'),
    url(r'^index$', index, name='index'),

    url(r'^logout$', logout, name='logout'),
    url(r'^perfil$', perfil, name='perfil'),
    url(r'^tareas$', tareas, name='tareas'),
    url(r'^confirmar$', confirmar, name='confirmar'),
    path('getTareas', getTareas, name='getTareas'),
    path('getTareasHechas', getTareasHechas, name='getTareasHechas'),
    path('login', Login.as_view(), name='login'),
    path('', Login.as_view(), name='login'),

]

way/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('apps.usuarios.urls')),
    url(r'^admin/', admin.site.urls),
     #url(r'^base/', include ('templates.base.urls')),
    url(r'^usuarios/', include ('apps.usuarios.urls')),
    url(r'^proyecto/', include ('apps.proyecto.urls')),
    url(r'^scrum/', include ('apps.scrum.urls')),

    path('xp/',include('apps.xp.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='usuarios/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='usuarios/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='usuarios/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='usuarios/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

#configuracion de rutas para imagenes
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/scrum/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.core import serializers

from apps.scrum.models import Pbacklog, Sbacklog, HistoriaUsuario, Sprint, Scrum, DailyMeeting, Sreview
from apps.scrum.forms import ScrumForm, PbacklogForm, HistoriaUsuarioForm, SbacklogForm, SprintForm, SreviewFrom
from apps.proyecto.views import get_data
from apps.usuarios.models import User
from apps.proyecto.models import Proyecto, ProUser
from django.db.models import Count, Q, Sum


@login_required
def scrum_list(request):
    backlog = Pbacklog.objects.all()
    contexto = {'pbacklog':backlog}
    return render(request, 'scrum/pbacklog_list',contexto)


@login_required
def pbacklog_list(request):
    backlog = Pbacklog.objects.all()
    contexto = {'pbacklog':backlog}
    return render(request, 'scrum/pbacklog_list.html',contexto)


@login_required
def historia_list(request):
    scrum = request.session['scrum']
    id_proyecto = Proyecto.objects.get(scrum__id=scrum)

    historia = HistoriaUsuario.objects.filter(id_pbacklog__id_scrum=scrum).annotate(
        tarea = Count('sbacklog__id')
    ).order_by('id')
    tareas = Sbacklog.objects.values('id','nombre','id_historia__quiero','n_horas').filter(id_historia__id_pbacklog__id_scrum=scrum)
    contexto = {
        'historia':historia,
        'tareas':tareas,
        'id_proyecto':id_proyecto
    }
    return render(request, 'scrum/historia_list.html', contexto)


@login_required
def sbacklog_list(request):
    scrum = request.session['scrum']
    sbacklog = Sbacklog.objects.filter(id_historia__id_pbacklog__id_scrum=scrum).order_by('id')
    contexto = {'sbacklog':sbacklog}
    return render(request, 'scrum/sbacklog_list.html', contexto)


@login_required
def scrum_crear(request):
    form = ScrumForm
    if request.method == 'POST':
        form = ScrumForm(data=request.POST)
        if form.is_valid():
           scrum =  form.save()
           # guardo el id del proyecto scrum
           request.session['scrum'] = scrum.id
           #return redirect('scrum:scrum_list')
           return redirect('scrum:pbacklog_crear')


    return render(request, 'scrum/scrum_crear.html',{'form':form})


@login_required
def pbacklog_crear(request):
    # creo un objeto con el ide del proyecto de scrum
    scrum = request.session['scrum']
    backlog = Pbacklog.objects.filter(id_scrum=scrum).annotate(
        hu=Count('historiausuario__id')
    ).order_by('id')

    if request.method == 'POST':
        form = PbacklogForm(data=request.POST)
        #print(form)
        if form.is_valid():
            form.save()
            print('paso')
            datos = {'datos': render_to_string('clean/scrum/table_epicas.html', {'pbacklog': backlog, 'scrum': scrum})}
            #return redirect('scrum:pbacklog_crear')
            return JsonResponse(datos)
        else:
            print('no se guardo')
    else:
        form = PbacklogForm

    return render(request, 'scrum/pbacklog_crear.html',{'form':form, 'scrum':scrum, 'pbacklog':backlog})


@login_required
def historia_crear(request):
    try:
        scrum = request.POST['scrum']
    except:
        scrum = ""

    if scrum:
        backlog = Pbacklog.objects.filter(id_scrum=scrum).annotate(
            hu=Count('historiausuario__id')
        ).order_by('id')
    try:
        sprint = request.POST['sprint']
    except:
        sprint = ""

    print('datos enviados para crear historias', request.POST)
    if request.method == 'POST':
        form = HistoriaUsuarioForm(data=request.POST)
        if form.is_valid():
            form.save()
            if sprint:
                id_pbacklog = request.POST['id_pbacklog']
                data = datos_sprint(id_pbacklog)

                datos = {
                    'tabla_general': render_to_string('clean/scrum/tabla_epicas_general_sprint.html',
                                                      {'requisitos': data['requisitos']}),
                    'tabla_editar_epica': render_to_string('clean/scrum/tabla_editar_epicas_sprint.html',
                                                           {'requisitos': data['requisitos']}),
                    'modulo_historia': render_to_string('clean/scrum/edicion_historias.html', {'historias': data['historias'],
                        'id_pbacklog': id_pbacklog}
                        )
                    }
                #datos = {'datos':'recibidos'}
            else:
                datos = {'datos': render_to_string('clean/scrum/table_epicas.html', {'pbacklog': backlog, 'scrum': scrum})}
            return JsonResponse(datos)
    else:
        form = HistoriaUsuarioForm
    #return render(request, 'scrum/pbacklog_crear.html', {'formHistoria': form})
    return pbacklog_crear(request)


@login_required
def sbacklog_crear(request):
    if request.method == 'POST':
        form = SbacklogForm(data=request.POST)
        if form.is_valid():
            form.save()

    id_pro = request.POST['id_pro']
    scrum = request.session['scrum']

    historia = HistoriaUsuario.objects.filter(id_pbacklog__id_scrum=scrum).annotate(
                tarea=Count('sbacklog__id')
            ).order_by('id')

    tareas = Sbacklog.objects.values('id','nombre', 'id_historia__quiero', 'n_horas').filter(
                id_historia__id_pbacklog__id_scrum=scrum)

    id_proyecto = Proyecto.objects.get(id=id_pro)

    contexto = {
                'historia': historia,
                'tareas': tareas,
                'id_proyecto': id_proyecto
            }

    datos = {'tabla_historias': render_to_string('clean/scrum/tabla_historias.html', contexto),
             'tabla_tareas': render_to_string('clean/scrum/tabla_tareas.html',
                                              {'tareas': tareas})
             }
    return JsonResponse(datos)


@login_required
def sbacklog_estado(request):

    form = SbacklogForm

    if request.method == 'POST':
        form = SbacklogForm(data=request.POST)
        if form.is_valid():
            sbacklog = Sbacklog()
            sbacklog.estado = form.cleaned_data['estado']
            sbacklog.save()
            return redirect('scrum:pbacklog_list')

    return redirect('scrum:pbacklog_list')


@login_required
def sprint(request, id):

    if request.method == 'POST':
        form = SprintForm(data=request.POST)
        if form.is_valid():
            form.save()
            requisito = form.cleaned_data['id_pbacklog']
            for r in requisito:
                Pbacklog.objects.filter(id=r.id).update(estado=False, confirmar=False)

            pro = request.POST['idIndex']
            request.session['proyectoIndex'] = pro
            return get_data(request, id)
            #return redirect('/proyecto/index2') #cambiar a path
    else:
        form = SprintForm

    proyecto_informacion = ProUser.objects.filter(proyecto=id).annotate(
        integrantes=Count('usuario'),
        numero_horas=Sum('horas')
    )

    integrantes = 0
    numero_horas = 0
    for i in proyecto_informacion:
        integrantes += i.integrantes
        numero_horas += i.numero_horas

    scrum = Scrum.objects.filter(proyecto=id)

    idscrum = scrum[0].id

    # Consultar si el pryecto ya tiene sprint creados
    try:
        dsprint = Sprint.objects.filter(id_scrum__proyecto=id).reverse()[0]
    except:
        dsprint = ""



    fecha = Proyecto.objects.values('f_inicio','f_fin').get(id=id)

    #sacar fechas y convertirlas a string
    if dsprint:
        fecha_inicio = datetime.strftime(dsprint.f_fin, '%Y-%m-%d')
    else:
        fecha_inicio = datetime.strftime(fecha['f_inicio'], '%Y-%m-%d')

    fecha_fin = datetime.strftime(fecha['f_fin'], '%Y-%m-%d')

    requisitos = Pbacklog.objects.filter(id_scrum=idscrum, confirmar=False).annotate(
        historias = Count('historiausuario__id'),
        historias_r = Count('historiausuario__id', filter=Q(historiausuario__estado=True)),
        tareas = Count('historiausuario__sbacklog__id'),
        tareas_r = Count('historiausuario__sbacklog__id', filter=Q(historiausuario__sbacklog__estado=True)),
        duracion = Sum('historiausuario__sbacklog__n_horas')
    ).order_by('id')
    contexto = {
        'form':form,
        'requisitos':requisitos,
        'idScrum':idscrum,
        'index':id,
        'fecha_inicio':fecha_inicio,
        'fecha_fin':fecha_fin,
        'numero_integrantes':integrantes,
        'numero_horas':numero_horas
    }
    return render(request, 'scrum/sprint_form.html', contexto)


@login_required
def dailymeeting(request):
    if request.method == 'POST':
        print(request.POST)

        ayer = request.POST['ayer']
        hoy = request.POST['hoy']
        problemas = request.POST['problemas']
        sp = request.POST['sprint']
        sprint = Sprint.objects.get(id=sp)
        us = request.user.pk
        usuario = User.objects.get(id=us)

        d = DailyMeeting.objects.create(ayer=ayer, hoy=hoy, problemas=problemas, sprint=sprint, usuario=usuario)
        d.save()

        return JsonResponse({'datos':'ready'})


@login_required
def sreview(request):
    if request.method == 'POST':
        id_proyecto = request.POST['id_proyecto']
        logros = request.POST['logros']
        id_pbacklog = request.POST['id_pbacklog'].split(',')
        observaciones = request.POST['observaciones']
        id_sprint = request.POST['sprint']

        sprint = Sprint.objects.get(id=id_sprint)
        form = Sreview.objects.create(logros=logros, observaciones=observaciones,sprint=sprint)
        print(request.POST)
        print('datos de requisitos',id_pbacklog)
        if id_pbacklog and id_pbacklog != ['']:
            for i in id_pbacklog:

templates/scrum/historia_crear.html
{% extends 'base/base.html'%}
{% block content %}

<div class="container">
    <form method="POST">
        {% csrf_token %}

        <div class="form-group">
            <label>Como</label>
            <input class="form-control" type="text" name="como_usuario">
        </div>
        <div class="form-group">
            <label>Quiero</label>
            <input class="form-control" type="text" name="quiero">
        </div>
        <div class="form-group">
            <label>Para</label>
            <input class="form-control" type="textarea" name="para">
        </div>
        <div class="form-group">
            <input type="hidden" name="id_pbacklog" value={{pbacklog}}>
        </div>

        <h1>pbacklog {{pbacklog}}</h1>
   
       
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a class="btn btn-danger" href="{% url 'scrum:pbacklog_list' %}">Cancelar</a>
        </div>
        
    </form>
    
</div>

{% endblock %}

templates/scrum/pbacklog_list.html
{% extends 'base/base.html'%}
{% block content %}


<table class="table">
    <thead>
        <tr>
            <td>Nombre</td>
            <td>Opcion</td>
        </tr>
    </thead>
    <tbody>
        {% if pbacklog %}
        
            {% for p in pbacklog %}
                <tr>
                    <td>{{ p.nombre }} </td>
                    <td> 
                        <a class="btn btn-primary" href="{% url 'scrum:historia_crear' p.id %}">H.U</a>
                    </td>
                </tr>
            {% endfor %}
    
        {% else %}
            <h1>No hay registros de proyectos</h1>
        
        {% endif %}
    </tbody>
</table>
<td> 
    <a class="btn btn-primary" href="{% url 'usuarios:index' %}">Inicio</a>
</td>
<td> 
    <a class="btn btn-primary" href="{% url 'scrum:historia_list' %}">Continuar</a>
</td>
{% endblock %}

templates/scrum/sbacklog_crear.html
{% extends 'base/base.html'%}
{% block content %}

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label>Descripción de la tarea</label>
            <input type="text" class="form-control" name="nombre">
        </div>

        <div class="form-group">
            <label>Numero de horas</label>
            <select name="n_horas" class="form-control" >
                <option value=2>2</option>
                <option value=4>4</option>
                <option value=6>6</option>
                <option value=8>8</option>
            </select>
        </div>

        <div>
            <input type="hidden" name="id_historia" value={{historia}}>
        </div>
        <h1>datos de historia {{historia}}</h1>

        <div class="form-group">
            <a class="btn btn-danger" href="{% url 'scrum:historia_list' %}">Cancelar</a>
            <button  type="submit" class="btn btn-primary" > Guardar </button>
        </div>
        
    </form>
    <td> 
        
    </td>
</div>

{% endblock %}

templates/scrum/sbacklog_list.html
{% extends 'base/base.html'%}
{% block content %}
 <html lang="en">
    <head>
        <!DOCTYPE html>
        <meta charset="UTF-8">
        {% block title %}
            <title>Listado de tareas</title>
        {% endblock %}
    </head>
    <body>
        <h2 style="text-align:center"><strong>Listado de Tareas</strong></h2>
    <br>
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <td>Tarea</td>
                        <td>Duracion en horas</td>
                        <td>Historia a la qe pertenece</td>
                    </tr>
                </thead>
                <tbody>
                    {% if sbacklog %}
                            {% for s in sbacklog %}
                                <tr>
                                    <td>{{ s.nombre }} </td>
                                    <td>{{ s.n_horas }} </td>
                                    <td>{{ s.id_historia }}</td>
                                </tr>
                            {% endfor %}
                    {% else %}
                        <h1>No hay registros de Tareas</h1>
                    {% endif %}
                </tbody>
            </table>
            <div>
                <a class="btn btn-danger" href="{% url 'scrum:historia_list' %}">Volver</a>
                <a class="btn btn-primary" href="{% url 'usuarios:index' %}">Inicio</a>
            </div>
        </div>
    </body>
</html>


<script>
 function terms_change(checkbox){
     if(checkbox.checked){
         alert('checkbox seleccionado');
         //<a href=""></a>
     }else{
        alert('checkbox deseleccionado');
     }    
 }
</script>
{% endblock %}

templates/scrum/scrum_crear.html
{% extends 'base/base.html'%}
{% block content %}

<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <div class="mx-auto">
            <button  type="submit" class="btn btn-primary" > Guardar </button>
        </div>
        
    </form>
</div>

{% endblock %}

templates/scrum/sprint_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>